"""
Factor 2: Variable-Name Proximity Context
==========================================
Weight: 35%

Evaluates the variable/key name immediately before = or : on the log line.
An exact HIGH_RISK name match → 1.0 (full score)
An exact LOW_RISK  name match → 0.0 (explicit safe signal)
No match or neutral name     → 0.3

HIGH_RISK set expanded from 22 → 150+ entries covering:
  - Generic security keywords (password, secret, token, key)
  - All major cloud vendor env var names (AWS, GCP, Azure)
  - All major AI/LLM vendor env var names (OpenAI, Anthropic, etc.)
  - All major DB vendor env var names (Mongo, Postgres, Redis, etc.)
  - All major messaging/payment vendor env var names
  - Framework-specific names (Django, Laravel, Rails, Spring)
"""

import re


class VarnameFactor:
    """
    Evaluates variable name proximity on the log line before = or :.
    """

    HIGH_RISK_VARNAMES = {
        # ── Generic security keywords ──────────────────────────────────────
        "password", "passwd", "pwd", "pass",
        "secret", "secret_key", "secret_token",
        "api_key", "apikey", "api_secret", "api_token",
        "auth_key", "auth_token", "auth_secret",
        "access_key", "access_token", "access_secret",
        "refresh_token", "id_token", "oauth_token",
        "private_key", "signing_key", "encryption_key",
        "master_key", "root_key", "root_password",
        "admin_key", "admin_password", "admin_secret",
        "user_password", "user_secret",
        "bearer", "bearer_token",
        "client_secret", "client_id_secret",
        "credentials", "credential",
        "token", "key", "secret_value",

        # ── JWT / Session ────────────────────────────────────────────────
        "jwt_secret", "jwt_key", "jwt_token",
        "session_secret", "session_key",
        "cookie_secret", "cookie_key",

        # ── AWS ─────────────────────────────────────────────────────────
        "aws_secret", "aws_secret_key", "aws_secret_access_key",
        "aws_access_key", "aws_access_key_id",
        "aws_session_token", "aws_key", "aws_token",
        "aws_api_key",

        # ── Azure ────────────────────────────────────────────────────────
        "azure_client_secret", "azure_subscription_key",
        "azure_account_key", "azure_storage_key",
        "azure_sas_token", "azure_connection_string",
        "azure_api_key",

        # ── GCP ──────────────────────────────────────────────────────────
        "google_api_key", "gcp_api_key", "google_application_credentials",
        "gcloud_api_key", "gemini_api_key",

        # ── DigitalOcean / Cloudflare ─────────────────────────────────
        "do_access_token", "digitalocean_token",
        "cloudflare_api_token", "cloudflare_api_key", "cf_api_key",

        # ── AI / LLM Providers ────────────────────────────────────────
        "openai_api_key", "openai_key", "openai_secret",
        "anthropic_api_key", "claude_api_key",
        "groq_api_key",
        "huggingface_token", "hugging_face_token", "hf_token",
        "deepseek_api_key",
        "mistral_api_key",
        "replicate_api_token",
        "elevenlabs_api_key",
        "jina_api_key",
        "pinecone_api_key",
        "xai_api_key", "grok_api_key",
        "perplexity_api_key",
        "cohere_api_key",
        "wandb_api_key",
        "nvidia_api_key",
        "langchain_api_key",

        # ── Version Control ──────────────────────────────────────────
        "github_token", "github_pat", "ghp_token",
        "gitlab_token", "gitlab_private_token",
        "bitbucket_password", "bitbucket_app_password",
        "npm_token", "npm_auth_token",
        "pypi_token",

        # ── Database ────────────────────────────────────────────────
        "db_password", "db_pass", "db_secret", "db_key",
        "database_password", "database_url", "database_uri",
        "mongo_uri", "mongodb_uri", "mongo_password", "mongo_pass",
        "postgres_password", "pg_password", "postgresql_password",
        "mysql_password", "mysql_root_password",
        "redis_password", "redis_auth", "redis_secret",
        "mssql_password", "sqlserver_password",
        "snowflake_password", "snowflake_private_key",
        "supabase_key", "supabase_service_key", "supabase_anon_key",
        "planetscale_password",
        "influxdb_token", "influx_token",
        "elasticsearch_password", "elastic_password",

        # ── Messaging ────────────────────────────────────────────────
        "slack_token", "slack_bot_token", "slack_signing_secret",
        "slack_webhook_url",
        "telegram_bot_token",
        "discord_token", "discord_bot_token", "discord_webhook",
        "twilio_auth_token", "twilio_token",
        "sendgrid_api_key", "sendgrid_key",
        "mailgun_api_key", "mailgun_key",
        "mailchimp_api_key",
        "resend_api_key",
        "pubnub_secret_key",
        "smtp_password", "mail_password", "email_password",

        # ── Payment ──────────────────────────────────────────────────
        "stripe_secret_key", "stripe_secret", "stripe_api_key",
        "stripe_webhook_secret",
        "paypal_secret", "paypal_client_secret",
        "razorpay_key_secret", "razorpay_secret",
        "braintree_private_key",
        "square_access_token", "square_secret",
        "shopify_secret", "shopify_shared_secret",
        "plaid_secret",

        # ── Frameworks ────────────────────────────────────────────────
        "secret_key_base",        # Rails
        "app_key",                # Laravel
        "app_secret",
        "django_secret_key",
        "spring_datasource_password",
        "spring_security_password",
        "flask_secret_key",

        # ── Infrastructure / DevOps ──────────────────────────────────
        "heroku_api_key",
        "terraform_token",
        "vault_token",
        "doppler_token",
        "ssh_private_key",
        "ssl_cert_key", "tls_private_key",
        "signing_secret",
        "webhook_secret",
        "encryption_secret",

        # auto-generated from 400+ detectors
        "gitlab_deploy_token",
        "zapier_webhook_url",
        "cloudant_iam",
        "hashicorp_vault_unseal_key",
        "packagecloudtoken",
        "iyzicoapikeys",
        "azure_service_management_certificate",
        "shopify_private_app_token",
        "zoomapijwt",
        "solr_credentials",
        "pepipostkey",
        "azurecommunicationservicesconnectionstring",
        "azure_iot_provisioning_connection_string",
        "sentryorgauthtoken",
        "azureeventhubkey",
        "odbc_connection_string",
        "clouderamodelkey",
        "sslmate_api_key",
        "elastic_api_key",
        "shopify_keys",
        "discordwebhookurl",
        "bunny_net_api_key",
        "ibm_cloud_key",
        "wepaytoken",
        "stripe_webhook_secret",
        "replicate_user_access_token",
        "gemfury_full_access_token",
        "slackusertoken",
        "apifyproxytoken",
        "bitfinex_keys",
        "codeclimatekey",
        "gitlabagentkubernetestoken",
        "jiratoken",
        "aiproxyapikey",
        "sourcegraphenterprisesubscriptiontoken",
        "finicity_authentication_keys",
        "visa_basic_auth",
        "zoom_api_jwt",
        "bitrisepersonalaccesstoken",
        "fireworks_ai_api_key",
        "plaid_access_token",
        "gitlab_enterprise_token",
        "splunkusercredentials",
        "deepseek_api_key",
        "chief_app_key",
        "pusherchannelskeys",
        "ovhkeys",
        "azure_subscription_key",
        "slackwebhookurl",
        "digitalocean_refresh_token_v1",
        "posthogprojectapikey",
        "tailscale_webhook_key",
        "tavily_api_key",
        "grafanacloudapikey",
        "pubnubpublishkey",
        "segmentworkspacekey",
        "googleoauth2keys",
        "azure_iot_device_connection_string",
        "oktatoken",
        "zohoapikey",
        "azuredevopspersonalaccesstoken",
        "shodankey",
        "datadogpersonalaccesstoken",
        "microsoftazurestorageaccountkey",
        "zoom_api_keys",
        "sourcegraph_enterprise_subscription_token",
        "clerk_webhook_token",
        "finicityauthenticationkeys",
        "ovh_keys",
        "payhere_merchant_secret",
        "vercelapiaccesstoken",
        "azuretexttranslationkey",
        "shodan_key",
        "posthogpersonalapikey",
        "azureservicebuskey",
        "sap_ai_core_credentials",
        "kubernetesdockersecret",
        "azure_document_intelligence_key",
        "authressaccesskey",
        "elasticsearchapikey",
        "keycloak_api_keys",
        "planetscale_oauth_token",
        "plaidaccesstoken",
        "instantly_api_key",
        "maxmind_license_key",
        "sonarqube_token",
        "slack_signing_secret",
        "fullcontact_key",
        "alibaba_cloud_keys",
        "scraper_api_key",
        "kairos_keys",
        "posthog_personal_api_key",
        "azure_active_directory_api_keys",
        "azure_relay_key",
        "slack_app_token",
        "azure_devops_personal_access_token",
        "mapboxtoken",
        "slackapptoken",
        "chiefappkey",
        "facebookaccesstoken",
        "qq_robot_api_keys",
        "jina_api_key",
        "google_cloud_express_api_key",
        "circleci_project_token",
        "agoraapikeys",
        "azure_event_grid_access_key",
        "postmarktoken",
        "azureiotprovisioningconnectionstring",
        "digitaloceanoauthapplicationtokenv1",
        "socket_dev_api_key",
        "squarecredentials",
        "aspnet_decryption_key",
        "vapiapikey",
        "solrcredentials",
        "artifactory_token_with_host",
        "nuget_api_key",
        "railssecretkeybase",
        "workato_api_key",
        "rapidapikey",
        "nessusagentkey",
        "surrealdbcloudjwttoken",
        "auth0_keys",
        "confluent_keys",
        "gitlab_incoming_mail_token",
        "k3stoken",
        "snowflakecredentials",
        "webex_app_keys",
        "zegocloud_secret",
        "azurequantumkey",
        "azurefunctionsappkey",
        "groqapikey",
        "pubnub_subscription_key",
        "bitbucketkeys",
        "sapaicorecredentials",
        "n8n_api_key",
        "sparkpostkey",
        "amadeusoauthcredentials",
        "algoliakeys",
        "oktatokenwithhost",
        "sourcegraphusergatewayaccesstoken",
        "ibmcloudkey",
        "krakenkeys",
        "adobeapikeys",
        "yandexpredictorapikey",
        "elevenlabsapikey",
        "cloudera_model_key",
        "mariadb_credentials",
        "paystack_key",
        "artifactory_access_token",
        "upstashrediscredentials",
        "gitguardian_onboarding_token",
        "dockerswarmunlockkey",
        "azurebatchcredentials",
        "easypost_api_key",
        "litellmapikeywithouthost",
        "tencentcloudkeys",
        "azureentraaccesstoken",
        "django_secret_key",
        "klaviyoapikey",
        "deepgramapikey",
        "azureservicemanagementcertificate",
        "infracost_api_key",
        "yousignapikey",
        "twilio_master_credentials",
        "azuresignalrconnectionstring",
        "cloudflare_api_token",
        "mssqlcredentials",
        "azure_computer_vision_key",
        "netlifytoken",
        "ubidots_token",
        "aikidoapioauth2credentials",
        "oraclecredentials",
        "artifactorybasicauthcredentials",
        "coralogixpersonalkey",
        "salesforce_refresh_tokens",
        "surgetoken",
        "gitlabrunnerauthenticationtoken",
        "confluentkeys",
        "kubernetesusercertificate",
        "mssql_credentials",
        "palantirjwt",
        "sourcegraphlicensekeytoken",
        "azureiotdeviceconnectionstring",
        "plivo_auth_tokens",
        "modelscope_api_key",
        "adoberefreshtoken",
        "azure_quantum_key",
        "dashscopetokenplanapikey",
        "snykkey",
        "scalrapiaccesstoken",
        "serpapitoken",
        "zohooauth2keys",
        "wiz_oauth_credentials",
        "coverallspersonaltoken",
        "pubnubsubscriptionkey",
        "bitbucket_http_access_token",
        "moneywaveapikey",
        "rails_master_key",
        "claudeapikey",
        "digitaloceanrefreshtokenv1",
        "awscognitoaccesstoken",
        "bitbucket_app_password",
        "azure_bot_direct_line_key",
        "sourcegraph_license_key_token",
        "vapid_key",
        "kraken_keys",
        "tomtom_api_key",
        "segment_workspace_key",
        "linkedin_oauth2_keys",
        "planetscaledatabasepassword",
        "momocredentials",
        "yandex_predictor_api_key",
        "paymob_api_key",
        "wireguardcredentials",
        "amadeus_oauth_credentials",
        "deepseekapikey",
        "litellm_api_key",
        "logflare_access_token",
        "mysql_credentials",
        "ibmcoshmaccredentials",
        "grafana_service_account_token_with_host",
        "obsidianapikey",
        "splunk_authentication_token",
        "tailscale_pre_auth_key",
        "twitter_access_keys",
        "cloudantcredentials",
        "aikido_ci_scanning_token",
        "facebookappkeys",
        "azurewebpubsubconnectionstring",
        "npmtoken",
        "aescipherkey",
        "twitch_api_keys",
        "slackconfigurationtoken",
        "recaptcha_key",
        "mercadopagoaccesstoken",
        "slackconfigurationrefreshtoken",
        "paypaloauth2keys",
        "azure_container_registry_key",
        "paystackkey",
        "zoomapijwtkeys",
        "alibabacloudkeys",
        "digitaloceantoken",
        "trellokeys",
        "tavilyapikey",
        "assemblyaiaccesstoken",
        "docker_credentials",
        "activemqcredentials",
        "mailgunprimarykey",
        "mattermost_personal_token",
        "payheremerchantsecret",
        "netlifytokenv2",
        "postman_api_key",
        "docusign_api_key",
        "azureactivedirectoryapikeys",
        "etsydeveloperkey",
        "azure_entra_app_secret",
        "googleapikey",
        "paymob_hmac_secret",
        "spotify_keys",
        "stitchapikey",
        "tailscalewebhookkey",
        "postgresqlcredentials",
        "gitlab_feature_flags_client_token",
        "verceloidctoken",
        "artifactory_basic_auth_credentials",
        "yookassa_api_key",
        "yousign_api_key",
        "yelpapikey",
        "pythonpackageindexkey",
        "yahoo_oauth2_keys",
        "1passwordserviceaccounttoken",
        "nessus_agent_key",
        "ftpcredentials",
        "dashscope_api_key",
        "supabase_jwt_secret",
        "snyk_key",
        "linodepersonalaccesstoken",
        "awsseskeys",
        "huaweiopenplatformkeys",
        "shippoapitoken",
        "neonapikey",
        "streamkeys",
        "sentry_org_auth_token",
        "githubapptoken",
        "azurefluidrelaykey",
        "mongodbcredentials",
        "litellmapikey",
        "shopifygenericapptoken",
        "azurecustomvisiontrainingkey",
        "elasticcloudcredentials",
        "mongodbatlaskeys",
        "circlecipersonaltoken",
        "artifactorytoken",
        "scraperapikey",
        "cloudsight_key",
        "vkontakteaccesstoken",
        "coinbasekeys",
        "workatoapikey",
        "volcengineapikey",
        "sonarqube_token_with_host",
        "pagerdutyauthorizationtoken",
        "datadog_application_key",
        "wireguard_credentials",
        "gitlab_feature_flags_client_token_with_project_id",
        "gemfuryfullaccesstoken",
        "gitlab_feed_token",
        "langfusecredentials",
        "artifactoryreferencetoken",
        "redshift_credentials",
        "azure_machine_learning_key",
        "lovable_git_token",
        "gitlab_trigger_token",
        "cloudsightkey",
        "cloudflareapitoken",
        "djangosecretkey",
        "azuresasurl",
        "microsoft_power_apps_webhook",
        "googlecloudexpressapikey",
        "outlookteamwebhook",
        "stream_keys",
        "npm_token",
        "azureiothubconnectionstring",
        "docker_swarm_join_token",
        "coinbase_keys",
        "azure_batch_credentials",
        "shippo_api_token",
        "vercel_blob_token",
        "artifactoryreferencetokenwithhost",
        "lovable_access_token",
        "qqrobotapikeys",
        "githuboauthtoken",
        "rails_secret_key_base",
        "gitlabenterprisetoken",
        "codeclimate_key",
        "flutterwaveapikey",
        "neon_api_key",
        "stabilityaiapikey",
        "influxdbtoken",
        "azurerelaykey",
        "fullstoryapikey",
        "kairoskeys",
        "zoomapikeys",
        "gemfury_full_access_token_without_username",
        "line_notify_token",
        "plaid_keys",
        "azuremapskey",
        "clearbitkey",
        "azure_functions_app_key",
        "aes_cipher_key",
        "amazon_mws_token",
        "betterauthsecret",
        "langchainapikey",
        "gitlabfeedtoken",
        "gocardlessapikey",
        "azureentraappsecret",
        "ionictoken",
        "notionintegrationtoken",
        "nucleiprivatekey",
        "mailjetkeys",
        "litellm_api_key_without_host",
        "fastlypersonaltoken",
        "linearoauth2keys",
        "sqreentoken",
        "stackhawkapikey",
        "influxdbtokenwithhost",
        "mailgun_domain_sending_key",
        "postmanapikey",
        "tailscaleapikey",
        "adobe_refresh_token",
        "gemfurydeployorpushtoken",
        "grafana_cloud_api_key",
        "azure_cache_for_redis_access_key",
        "postgresql_credentials",
        "redisserverpassword",
        "ftp_credentials",
        "modelscopeapikey",
        "ibm_cos_hmac_credentials",
        "squaretoken",
        "lovableaccesstoken",
        "kimiapikey",
        "paymobapikey",
        "intercom_access_token",
        "planetscaleoauthtoken",
        "azure_signalr_connection_string",
        "messagebird_key",
        "linenotifytoken",
        "lacework_api_keys",
        "salesforce_oauth2_keys",
        "github_oauth_app_keys",
        "zoho_oauth2_keys",
        "keycloak_access_token",
        "pushbulletapikey",
        "pulumiaccesstoken",
        "packagecloud_token",
        "sshcredentials",
        "jenkinsapitoken",
        "gitlabfeatureflagsclienttoken",
        "wechatappkeys",
        "apifytoken",
        "clipdropapikey",
        "shopify_generic_app_token",
        "keycloakaccesstoken",
        "azuremixedrealitykey",
        "azure_ai_search_key",
        "zendesktoken",
        "paymob_secret_key",
        "groq_api_key",
        "azure_video_indexer_key",
        "fullcontactkey",
        "dwollakeys",
        "gitea_access_token",
        "azureimmersivereaderkey",
        "discord_webhook_url",
        "azure_text_translation_key",
        "plivoauthtokens",
        "serpapi_token",
        "typeform_api_token",
        "stability_ai_api_key",
        "puttyprivatekey",
        "clockworkkey",
        "uber_server_token",
        "gitguardianonboardingtoken",
        "salesforceoauth2keys",
        "mariadbcredentials",
        "azuresubscriptionkey",
        "mailjet_keys",
        "wizoauthcredentials",
        "sendinblue_key",
        "hashicorp_consul_acl_token",
        "grafana_personal_token",
        "cloudinaryapikeys",
        "murf_api_key",
        "jirabasicauth",
        "azuremachinelearningkey",
        "paypalbraintreekeys",
        "planetscale_service_token",
        "gitlabincomingmailtoken",
        "grafana_service_account_token",
        "webexappkeys",
        "clearbit_key",
        "hashicorpconsulacltoken",
        "herokuplatformkey",
        "splunkauthenticationtoken",
        "db2credentials",
        "deepgram_api_key",
        "clojars_deploy_token",
        "ldap_credentials",
        "oracle_credentials",
        "auth0keys",
        "azure_speech_services_key",
        "langchain_api_key",
        "vapidkey",
        "deepl_pro_api_keys",
        "grafanaserviceaccounttokenwithhost",
        "openaiserviceaccount",
        "nuclei_private_key",
        "authress_access_key",
        "authentik_api_token",
        "datadogapicredentials",
        "supabase_service_role_jwt",
        "azure_language_api_key",
        "fireworksaiapikey",
        "gitguardian_test_token_checked",
        "sqreen_token",
        "zoomsdkkeys",
        "gitlab_runner_authentication_token",
        "paypal_oauth2_keys",
        "xrayaccesstoken",
        "aspnetvalidationkey",
        "gitlab_token",
        "azure_fluid_relay_key",
        "pingidentitykeys",
        "zendesk_token",
        "keycloakrefreshtoken",
        "azureentraidtoken",
        "mailersendapikey",
        "azure_sas_url",
        "adobe_api_keys",
        "activemq_credentials",
        "azurecomputervisionkey",
        "dwolla_keys",
        "coveoapikey",
        "terraformcloudtoken",
        "openclawauthtoken",
        "socketdevapikey",
        "frameiotoken",
        "supabaseservicerolejwt",
        "putty_private_key",
        "tailscale_scim_key",
        "amqp_credentials",
        "shopifyprivateapptoken",
        "gitguardianincidenttoken",
        "sourcegraph_user_gateway_access_token",
        "clarifaikey",
        "gitlaboauthapplicationtoken",
        "microsoftpowerappswebhook",
        "aikidociscanningtoken",
        "openai_access_token",
        "polyapiapikey",
        "azure_open_ai_api_key",
        "cloudsmith_entitlement_token",
        "polyapi_api_key",
        "codacy_api_credentials",
        "netlify_token_v2",
        "artifactory_token",
        "aws_ses_keys",
        "wechat_app_keys",
        "clipdrop_api_key",
        "azuresqlcredentials",
        "buildkite_api_token",
        "typeformapitoken",
        "datadogapplicationkey",
        "gemfury_deploy_or_push_token",
        "facebook_app_keys",
        "duo_keys",
        "huawei_open_platform_keys",
        "azure_mixed_reality_key",
        "anthropicadminkey",
        "gitguardian_incident_token",
        "gitlabfeatureflagsclienttokenwithprojectid",
        "stackhawk_api_key",
        "tailscale_api_key",
        "github_app_keys",
        "supabasejwtsecret",
        "pushbullet_api_key",
        "tailscalescimkey",
        "clerkwebhooktoken",
        "frame_io_token",
        "google_oauth2_keys",
        "kie_ai_api_key",
        "splunk_user_credentials",
        "smtp_credentials",
        "sslmateapikey",
        "recaptchakey",
        "mailgundomainsendingkey",
        "pineconeapikey",
        "sonarqubetokenwithhost",
        "anypointkeys",
        "zegocloudsecret",
        "zoho_api_key",
        "etsy_developer_key",
        "dashscope_token_plan_api_key",
        "openaiaccesstoken",
        "salesforcerefreshtokens",
        "aivenapikey",
        "digitalocean_token",
        "linkedinoauth2keys",
        "volcengine_api_key",
        "atlassian_access_token",
        "birdeye_api_key",
        "bitfinexkeys",
        "vkontakte_access_token",
        "cartesiaapikey",
        "momo_credentials",
        "nx_cloud_token",
        "kubernetes_user_certificate",
        "cometapikey",
        "africas_talking_api_key",
        "codacyapicredentials",
        "dockercredentials",
        "scalr_api_access_token",
        "codecovapikey",
        "microsoftazurestorageconnectionstring",
        "webflow_api_token",
        "gitguardian_platform_magic_link",
        "fastly_personal_token",
        "hashicorpvaulttoken",
        "opencode_api_key",
        "surge_token",
        "e2b_api_key",
        "azure_custom_vision_training_key",
        "nugetapikey",
        "mailchimpapikey",
        "influxdb_token",
        "visabasicauth",
        "datadog_api_credentials",
        "netlify_token",
        "githubappkeys",
        "sap_oauth_credentials",
        "azure_web_pubsub_connection_string",
        "tailscalepreauthkey",
        "supabase_api_key",
        "uberservertoken",
        "pubnubsecretkey",
        "n8napikey",
        "figmapersonalaccesstoken",
        "ssh_credentials",
        "stripe_keys",
        "travis_personal_token",
        "virustotal_api_key",
        "obsidian_api_key",
        "huggingfaceuseraccesstoken",
        "akamaiapicredentials",
        "yahoooauth2keys",
        "cockroachdb_api_key",
        "elasticapikey",
        "rediscredentials",
        "dashscopeapikey",
        "gemfury_deploy_or_push_token_without_username",
        "coralogix_personal_key",
        "neoloadwebaccesstoken",
        "pagerduty_authorization_token",
        "terraform_cloud_token",
        "mem0_api_key",
        "snowflake_credentials",
        "artifactoryaccesstoken",
        "mongodb_atlas_keys",
        "algolia_keys",
        "azureopenaiapikey",
        "databricksauthenticationtoken",
        "firebaseidtoken",
        "python_package_index_key",
        "vercel_api_access_token",
        "azure_service_bus_key",
        "upstash_redis_credentials",
        "outlook_team_webhook",
        "grafanaserviceaccounttoken",
        "laceworkapikeys",
        "keycloak_refresh_token",
        "coder_session_token",
        "wepay_token",
        "jinaapikey",
        "jira_basic_auth",
        "cloudflare_r2_token",
        "cloudflarer2token",
        "cockroachdbapikey",
        "aws_cognito_access_token",
        "twitteraccesskeys",
        "paymobhmacsecret",
        "gitguardiantesttokenchecked",
        "scaleway_token",
        "mercadopagooauth",
        "xray_access_token",
        "github_enterprise_token",
        "coze_access_token",
        "xendit_api_key",
        "yelp_api_key",
        "agora_api_keys",
        "akamai_api_credentials",
        "bitbucket_keys",
        "hashicorp_vault_token",
        "canva_integration_oauth2",
        "gitlab_scim_token",
        "pubnub_publish_key",
        "codacyprojecttoken",
        "assemblyai_access_token",
        "fernetkey",
        "okta_token",
        "azure_entra_access_token",
        "codersessiontoken",
        "square_token",
        "ubidotstoken",
        "amqpcredentials",
        "dropboxkey",
        "elastic_search_api_key",
        "slack_configuration_token",
        "odoo_external_api_key",
        "mailgun_primary_key",
        "pingidentity_keys",
        "railsmasterkey",
        "vapi_api_key",
        "stripewebhooksecret",
        "dropboxappcredentials",
        "gitlabdeploytoken",
        "lovablegittoken",
        "zoom_sdk_keys",
        "smtpcredentials",
        "openclaw_auth_token",
        "azureappconfigurationconnectionstring",
        "harness_api_key",
        "grafanapersonaltoken",
        "jira_token",
        "redis_credentials",
        "slack_configuration_refresh_token",
        "azure_apim_gateway_key",
        "vonagekeys",
        "odbcconnectionstring",
        "bunnynetapikey",
        "kimi_api_key",
        "mercado_pago_oauth",
        "pusher_channels_keys",
        "kinde_oauth_credentials",
        "linode_personal_access_token",
        "okta_keys",
        "azurespeechserviceskey",
        "fishaudioapikey",
        "africastalkingapikey",
        "jetbrains_teamcity_config_value",
        "aiproxy_api_key",
        "twitchapikeys",
        "anypoint_keys",
        "gitguardianplatformmagiclink",
        "githubenterprisetoken",
        "figma_personal_access_token",
        "dynatrace_token",
        "k3s_token",
        "aspnetdecryptionkey",
        "cloudant_credentials",
        "mattermostpersonaltoken",
        "moneywave_api_key",
        "docusignapikey",
        "sendinbluekey",
        "azure_app_configuration_connection_string",
        "smbcredentials",
        "vultr_key",
        "coveo_api_key",
        "equinixauthenticationtoken",
        "mercado_pago_access_token",
        "vercel_oidc_token",
        "artifactory_reference_token_with_host",
        "github_app_token",
        "base64awsseskeys",
        "atlassianauthkey",
        "azure_communication_services_connection_string",
        "docker_swarm_unlock_key",
        "githuboauthappkeys",
        "sendgridkey",
        "artifactorymasterkey",
        "zapierwebhookurl",
        "dockerswarmjointoken",
        "virustotalapikey",
        "azure_sql_credentials",
        "elevenlabs_api_key",
        "slack_webhook_url",
        "freshdeskmessagingtoken",
        "bitriseworkspaceapitoken",
        "datadog_personal_access_token",
        "deeplproapikeys",
        "gemfuryfullaccesstokenwithoutusername",
        "retellapikey",
        "travispersonaltoken",
        "atlassianaccesstoken",
        "hashicorpvaultunsealkey",
        "codecov_api_key",
        "payhereappcredentials",
        "openai_service_account",
        "aikido_api_oauth2_credentials",
        "tailscale_oauth_key",
        "flutterwave_api_key",
        "bitbucketapppassword",
        "anthropic_admin_key",
        "artifactory_reference_token",
        "digitalocean_oauth_application_token_v1",
        "gitlab_agent_kubernetes_token",
        "okta_token_with_host",
        "postmark_token",
        "vonage_keys",
        "jenkins_api_token",
        "bitbuckethttpaccesstoken",
        "paypal_braintree_keys",
        "deno_account_token",
        "canvaintegrationoauth2",
        "giteaaccesstoken",
        "clockwork_key",
        "ibmapiconnectcredentials",
        "buildkiteapitoken",
        "pepipost_key",
        "intercomaccesstoken",
        "digitalocean_oauth_application_keys",
        "neoload_web_access_token",
        "mysqlcredentials",
        "birdeyeapikey",
        "equinix_authentication_token",
        "maxmindlicensekey",
        "planetscale_database_password",
        "messagebirdkey",
        "azurevideoindexerkey",
        "supabaseapikey",
        "xaiapikey",
        "azureapimgatewaykey",
        "square_credentials",
        "bitrise_personal_access_token",
        "keycloakapikeys",
        "shopifykeys",
        "dropbox_key",
        "langfuse_credentials",
        "google_api_key",
        "base64_aws_ses_keys",
        "aspnet_validation_key",
        "jetbrainsteamcityconfigvalue",
        "azure_maps_key",
        "cloudantiam",
        "redis_server_password",
        "artifactorytokenwithhost",
        "proxmox_api_token",
        "zillow_key",
        "scalewaytoken",
        "murfapikey",
        "claude_api_key",
        "kieaiapikey",
        "plaidkeys",
        "azure_immersive_reader_key",
        "freshdesk_messaging_token",
        "gemfurydeployorpushtokenwithoutusername",
        "buildkite_agent_token",
        "cozeaccesstoken",
        "ldapcredentials",
        "azure_entra_id_token",
        "mem0apikey",
        "coveralls_personal_token",
        "sparkpost_key",
        "apify_proxy_token",
        "dropbox_app_credentials",
        "slack_user_token",
        "pingdomtoken",
        "circleciprojecttoken",
        "logflareaccesstoken",
        "db2_credentials",
        "gitlabtriggertoken",
        "gocardless_api_key",
        "harnessapikey",
        "influxdb_token_with_host",
        "azurecacheforredisaccesskey",
        "pulumi_access_token",
        "vultrkey",
        "fish_audio_api_key",
        "proxmoxapitoken",
        "linear_oauth2_keys",
        "1password_service_account_token",
        "firebase_id_token",
        "aiven_api_key",
        "azure_event_hub_key",
        "surrealdb_cloud_jwt_token",
        "trello_keys",
        "tailscaleoauthkey",
        "yookassaapikey",
        "freshdesk_api_token",
        "smb_credentials",
        "hugging_face_user_access_token",
        "azurebotdirectlinekey",
        "ibm_api_connect_credentials",
        "clarifai_key",
        "spotifykeys",
        "azurehealthinsightskey",
        "zillowkey",
        "cloudsmithentitlementtoken",
        "facebook_access_token",
        "hunterapikey",
        "sonarqubetoken",
        "instantlyapikey",
        "sapoauthcredentials",
        "e2bapikey",
        "apify_token",
        "kubernetes_docker_secret",
        "odooexternalapikey",
        "better_auth_secret",
        "payhere_app_credentials",
        "freshdeskapitoken",
        "mailchimp_api_key",
        "vercelblobtoken",
        "elastic_cloud_credentials",
        "gitlabscimtoken",
        "retell_api_key",
        "clojarsdeploytoken",
        "notion_integration_token",
        "deeplfreeapikeys",
        "zoom_api_jwt_keys",
        "cartesia_api_key",
        "comet_api_key",
        "databricks_authentication_token",
        "microsoft_azure_storage_account_key",
        "atlassian_auth_key",
        "nylas_api_key",
        "azurecontainerregistrykey",
        "xenditapikey",
        "ionic_token",
        "codacy_project_token",
        "hunter_api_key",
        "infracostapikey",
        "mailersend_api_key",
        "opencodeapikey",
        "azurelanguageapikey",
        "cloudinary_api_keys",
        "webflowapitoken",
        "buildkiteagenttoken",
        "rapidapi_key",
        "iyzico_api_keys",
        "github_oauth_token",
        "fullstory_api_key",
        "sanity_token",
        "circleci_personal_token",
        "discord_bot_token",
        "dynatracetoken",
        "azuredocumentintelligencekey",
        "duokeys",
        "sanitytoken",
        "pingdom_token",
        "redshiftcredentials",
        "nxcloudtoken",
        "mongodb_credentials",
        "sendgrid_key",
        "stitch_api_key",
        "azureeventgridaccesskey",
        "oktakeys",
        "klaviyo_api_key",
        "authentikapitoken",
        "discordbottoken",
        "planetscaleservicetoken",
        "tomtomapikey",
        "bitrise_workspace_api_token",
        "slacksigningsecret",
        "amazonmwstoken",
        "easypostapikey",
        "replicateuseraccesstoken",
        "kindeoauthcredentials",
        "gitlab_oauth_application_token",
        "heroku_platform_key",
        "palantir_jwt",
        "pinecone_api_key",
        "tencent_cloud_keys",
        "digitaloceanoauthapplicationkeys",
        "artifactory_master_key",
        "paymobsecretkey",
        "fernet_key",
        "gitlabtoken",
        "mapbox_token",
        "x_ai_api_key",
        "posthog_project_api_key",
        "denoaccounttoken",
        "microsoft_azure_storage_connection_string",
        "pubnub_secret_key",
        "twiliomastercredentials",
        "deepl_free_api_keys",
        "azure_health_insights_key",
        "nylasapikey",
        "stripekeys",
        "azureaisearchkey",
        "azure_iot_hub_connection_string",
    }

    LOW_RISK_VARNAMES = {
        # ── Observability / Request IDs ──────────────────────────────
        "order_id", "request_id", "trace_id", "correlation_id",
        "transaction_id", "event_id", "message_id",
        "span_id", "parent_id",

        # ── User / Session IDs ───────────────────────────────────────
        "user_id", "session_id", "account_id", "org_id",
        "tenant_id", "workspace_id", "team_id",

        # ── Network / System ─────────────────────────────────────────
        "host", "hostname", "port", "path", "url", "endpoint",
        "ip_address", "ip", "domain",
        "method", "status", "status_code",

        # ── Timing / Metrics ─────────────────────────────────────────
        "timestamp", "created_at", "updated_at", "expires_at",
        "duration", "latency", "timeout", "delay",
        "count", "total", "amount", "size",

        # ── Log Metadata ─────────────────────────────────────────────
        "level", "severity", "logger", "service", "component",
        "version", "build", "environment", "env",
        "retry", "attempt", "iteration",
    }

    def evaluate(self, line: str) -> float:
        line_lower = line.lower()
        keys = re.findall(r"\b([a-z0-9_\-]+)\s*[=:]", line_lower)
        if not keys:
            return 0.0
        
        has_low = False
        for k in keys:
            if k in self.HIGH_RISK_VARNAMES:
                return 1.0
            if k in self.LOW_RISK_VARNAMES:
                has_low = True
                
        return 0.0
