"""
Generated Specific Detectors V2
================================
Auto-generated from 464 specific detector profiles using exact HTML metadata.
Uses KV-bound regexes to prevent Pass 2 False Positives.
"""

import re

GENERATED_SPECIFIC_DETECTORS = [
    (re.compile(r"ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}"), "1Password Service Account Token", "1Password", "secret_management", 0.8),
    (re.compile(r"(?i)(?:activemq.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Activemq Credentials", "Apache", "data_storage", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Adobe Api Keys", "Adobe", "other", 0.8),
    (re.compile(r"refresh[_-]?token(=| =|:| :)"), "Adobe Refresh Token", "Adobe", "other", 0.8),
    (re.compile(r"(?i)(?:aes.*?cipher.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Aes Cipher Key", "Unknown", "private_key", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Africas Talking Api Key", "Africa", "messaging_system", 0.85),
    (re.compile(r"(?:agora).{0,40}\b([a-z0-9]{32})\b"), "Agora Api Keys", "Agora", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:aikido.*?api.*?oauth2.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Aikido Api Oauth2 Credentials", "Aikido", "ai", 0.8),
    (re.compile(r"(?i)(?:aikido.*?ci.*?scanning.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Aikido Ci Scanning Token", "Aikido", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Aiproxy Api Key", "AIProxy", "ai", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Aiven Api Key", "Aiven", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:akamai.*?api.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Akamai Api Credentials", "Akamai", "cdn", 0.85),
    (re.compile(r"(?i)(?:algolia.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Algolia Keys", "Algolia", "data_storage", 0.8),
    (re.compile(r"(?i)(?:alibaba.*?cloud.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Alibaba Cloud Keys", "Alibaba", "cloud_provider", 0.85),
    (re.compile(r"(?i)(?:amadeus.*?oauth.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Amadeus Oauth Credentials", "Amadeus", "other", 0.8),
    (re.compile(r"(?i)(?:amazon.*?mws.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Amazon Mws Token", "Amazon", "payment_system", 0.85),
    (re.compile(r"(?i)(?:amqp.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Amqp Credentials", "Unknown", "data_storage", 0.85),
    (re.compile(r"(?i)(?:anypoint.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Anypoint Keys", "MuleSoft", "identity_provider", 0.8),
    (re.compile(r"\b(apify\_api\_[a-zA-Z-0-9]{36})\b"), "Apify Proxy Token", "Apify", "ai", 0.8),
    (re.compile(r"\b(apify\_api\_[a-zA-Z-0-9]{36})\b"), "Apify Token", "Apify", "other", 0.85),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Artifactory Access Token", "JFrog", "package_registry", 0.85),
    (re.compile(r"(artifactory.{0,50}(\"|')?[a-zA-Z0-9=]{112}(\"|')?)"), "Artifactory Basic Auth Credentials", "JFrog", "package_registry", 0.85),
    (re.compile(r"(artifactory.{0,50}(\"|')?[a-zA-Z0-9=]{112}(\"|')?)"), "Artifactory Master Key", "JFrog", "package_registry", 0.8),
    (re.compile(r"\bcmVmd[A-Za-z0-9]{59}\b"), "Artifactory Reference Token", "JFrog", "package_registry", 0.8),
    (re.compile(r"\bcmVmd[A-Za-z0-9]{59}\b"), "Artifactory Reference Token With Host", "JFrog", "package_registry", 0.8),
    (re.compile(r"(artifactory.{0,50}(\"|')?[a-zA-Z0-9=]{112}(\"|')?)"), "Artifactory Token", "JFrog", "package_registry", 0.85),
    (re.compile(r"(?:host).{0,40}\b([a-z0-9]{14})\b"), "Artifactory Token With Host", "JFrog", "package_registry", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Aspnet Decryption Key", "Microsoft", "private_key", 0.8),
    (re.compile(r"(?i)(?:aspnet.*?validation.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Aspnet Validation Key", "Microsoft", "private_key", 0.8),
    (re.compile(r"(?:assemblyai).{0,40}\b([0-9a-z]{32})\b"), "Assemblyai Access Token", "AssemblyAI", "ai", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Atlassian Access Token", "Atlassian", "collaboration_tool", 0.8),
    (re.compile(r"(?i)(?:atlassian.*?auth.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Atlassian Auth Key", "Atlassian", "collaboration_tool", 0.8),
    (re.compile(r"(?i)(?:auth0.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Auth0 Keys", "Auth0", "identity_provider", 0.8),
    (re.compile(r"(?i)(?:authentik.*?api.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Authentik Api Token", "Authentik", "other", 0.8),
    (re.compile(r"(?i)(?:authress.*?access.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Authress Access Key", "Authress", "identity_provider", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Aws Cognito Access Token", "Amazon", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Active Directory Api Keys", "Microsoft", "identity_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?ai.*?search.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Ai Search Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?apim.*?gateway.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Apim Gateway Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?batch.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Batch Credentials", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Bot Direct Line Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Cache For Redis Access Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Computer Vision Key", "Microsoft", "ai", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Container Registry Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Custom Vision Training Key", "Microsoft", "ai", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Azure Devops Personal Access Token", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?document.*?intelligence.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Document Intelligence Key", "Microsoft", "ai", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Entra App Secret", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?entra.*?id.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Entra Id Token", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?event.*?grid.*?access.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Event Grid Access Key", "Microsoft", "data_storage", 0.8),
    (re.compile(r"(?i)(?:azure.*?event.*?hub.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Event Hub Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?fluid.*?relay.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Fluid Relay Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?functions.*?app.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Functions App Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?health.*?insights.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Health Insights Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?immersive.*?reader.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Immersive Reader Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Iot Hub Connection String", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Iot Provisioning Connection String", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Azure Language Api Key", "Microsoft", "ai", 0.8),
    (re.compile(r"(?i)(?:azure.*?machine.*?learning.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Machine Learning Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?maps.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Maps Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?mixed.*?reality.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Mixed Reality Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"\b(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})\b|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\x60'\"\s;]|\\[nr]|$)"), "Azure Open Ai Api Key", "Microsoft", "ai", 0.8),
    (re.compile(r"(?i)(?:azure.*?quantum.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Quantum Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?relay.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Relay Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?service.*?bus.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Service Bus Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?service.*?management.*?certificate)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Service Management Certificate", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Signalr Connection String", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Speech Services Key", "Microsoft", "ai", 0.8),
    (re.compile(r"(?i)(?:azure.*?sql.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Sql Credentials", "Microsoft", "data_storage", 0.8),
    (re.compile(r"(?i)(?:azure.*?subscription.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Subscription Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:azure.*?text.*?translation.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Text Translation Key", "Microsoft", "ai", 0.8),
    (re.compile(r"(?i)(?:azure.*?video.*?indexer.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Azure Video Indexer Key", "Microsoft", "ai", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Azure Web Pubsub Connection String", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:base64.*?aws.*?ses.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Base64 Aws Ses Keys", "Amazon", "cloud_provider", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Better Auth Secret", "Better", "identity_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Birdeye Api Key", "Birdeye", "cryptos", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Bitbucket Http Access Token", "Bitbucket", "version_control_platform", 0.8),
    (re.compile(r"(?i)(?:bitbucket.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Bitbucket Keys", "Bitbucket", "version_control_platform", 0.8),
    (re.compile(r"(?:bitfinex).{0,40}\b([A-Za-z0-9_-]{43})\b"), "Bitfinex Keys", "Bitfinex", "cryptos", 0.8),
    (re.compile(r"(?i)(?:bitrise.*?workspace.*?api.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Bitrise Workspace Api Token", "Bitrise", "ci_cd", 0.8),
    (re.compile(r"(?:buildkite).{0,40}\b([a-z0-9]{40})\b"), "Buildkite Api Token", "Buildkite", "ci_cd", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Bunny Net Api Key", "Bunny", "cdn", 0.8),
    (re.compile(r"(?i)(?:canva.*?integration.*?oauth2)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Canva Integration Oauth2", "Canva", "collaboration_tool", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Cartesia Api Key", "Cartesia", "ai", 0.85),
    (re.compile(r"(?i)(?:chief.*?app.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Chief App Key", "Chief", "other", 0.8),
    (re.compile(r"(?:circle).{0,40}([a-fA-F0-9]{40})"), "Circleci Personal Token", "CircleCI", "ci_cd", 0.8),
    (re.compile(r"(?:circle).{0,40}([a-fA-F0-9]{40})"), "Circleci Project Token", "CircleCI", "ci_cd", 0.8),
    (re.compile(r"(?i)(?:clarifai.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Clarifai Key", "Clarifai", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Claude Api Key", "Anthropic", "ai", 0.85),
    (re.compile(r"(?:clearbit).{0,40}\b([0-9a-z_]{35})\b"), "Clearbit Key", "Clearbit", "crm", 0.8),
    (re.compile(r"(?i)(?:clerk.*?webhook.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Clerk Webhook Token", "Clerk", "identity_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Clipdrop Api Key", "Unknown", "ai", 0.8),
    (re.compile(r"(?i)(?:clockwork.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Clockwork Key", "Clockwork", "messaging_system", 0.8),
    (re.compile(r"deploy[_-]?token(=| =|:| :)"), "Clojars Deploy Token", "Clojars", "package_registry", 0.85),
    (re.compile(r"(?i)(?:cloudant.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Cloudant Credentials", "IBM", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:cloudant.*?iam)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Cloudant Iam", "IBM", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:cloudera.*?model.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Cloudera Model Key", "Cloudera", "other", 0.8),
    (re.compile(r"(?:cloudflare).{0,40}\b([A-Za-z0-9_-]{40})\b"), "Cloudflare Api Token", "Unknown", "generic", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Cloudinary Api Keys", "Cloudinary", "cdn", 0.8),
    (re.compile(r"(?i)(?:cloudsight.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Cloudsight Key", "CloudSight", "other", 0.8),
    (re.compile(r"(?i)(?:cloudsmith.*?entitlement.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Cloudsmith Entitlement Token", "Cloudsmith", "data_storage", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Cockroachdb Api Key", "Cockroach", "unknown_or_deprecated", 0.8),
    (re.compile(r"(?:codacy).{0,40}\b([0-9A-Za-z]{20})\b"), "Codacy Api Credentials", "Codacy", "code_analysis", 0.8),
    (re.compile(r"(?:codacy).{0,40}\b([0-9A-Za-z]{20})\b"), "Codacy Project Token", "Codacy", "code_analysis", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Codeclimate Key", "Code", "code_analysis", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Codecov Api Key", "Codecov", "code_analysis", 0.8),
    (re.compile(r"(?i)(?:coder.*?session.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Coder Session Token", "Coder", "other", 0.8),
    (re.compile(r"(?:coinbase).{0,40}\b([a-zA-Z-0-9]{64})\b"), "Coinbase Keys", "Coinbase", "cryptos", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Comet Api Key", "Comet", "ai", 0.8),
    (re.compile(r"(?i)(?:confluent.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Confluent Keys", "Confluent", "collaboration_tool", 0.8),
    (re.compile(r"personal[_-]?key(=| =|:| :)"), "Coralogix Personal Key", "Coralogix", "monitoring", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Coveo Api Key", "Unknown", "ai", 0.8),
    (re.compile(r"(?:coveralls).{0,40}\b([a-zA-Z0-9-]{37})\b"), "Coveralls Personal Token", "Coveralls", "code_analysis", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Coze Access Token", "Coze", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Dashscope Api Key", "Alibaba", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Dashscope Token Plan Api Key", "Alibaba", "ai", 0.8),
    (re.compile(r"dapi[a-f0-9]{32}\b"), "Databricks Authentication Token", "Databricks", "other", 0.85),
    (re.compile(r"(?i)(?:datadog.*?api.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Datadog Api Credentials", "Datadog", "monitoring", 0.8),
    (re.compile(r"(?i)(?:datadog.*?application.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Datadog Application Key", "Datadog", "monitoring", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Datadog Personal Access Token", "Datadog", "monitoring", 0.8),
    (re.compile(r"(?i)(?:db2.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Db2 Credentials", "IBM", "data_storage", 0.8),
    (re.compile(r"(?:deepgram).{0,40}\b([0-9a-z]{40})\b"), "Deepgram Api Key", "Deepgram", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Deepl Free Api Keys", "DeepL", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Deepl Pro Api Keys", "DeepL", "other", 0.8),
    (re.compile(r"(?i)(?:deno.*?account.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Deno Account Token", "Deno", "remote_access", 0.8),
    (re.compile(r"(?i)(?:digitalocean.*?oauth.*?application.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Digitalocean Oauth Application Keys", "DigitalOcean", "cloud_provider", 0.8),
    (re.compile(r"(?:digitalocean).{0,40}\b([A-Za-z0-9_-]{64})\b"), "Digitalocean Token", "DigitalOcean", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:docker.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Docker Credentials", "Docker", "package_registry", 0.85),
    (re.compile(r"(?i)(?:docker.*?swarm.*?join.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Docker Swarm Join Token", "Docker", "other", 0.85),
    (re.compile(r"(?i)(?:docker.*?swarm.*?unlock.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Docker Swarm Unlock Key", "Docker", "other", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Docusign Api Key", "Docusign", "other", 0.8),
    (re.compile(r"\b(sl\.[A-Za-z0-9\-\_]{130,140})\b"), "Dropbox App Credentials", "Dropbox", "data_storage", 0.8),
    (re.compile(r"\b(sl\.[A-Za-z0-9\-\_]{130,140})\b"), "Dropbox Key", "Dropbox", "data_storage", 0.85),
    (re.compile(r"(?i)(?:duo.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Duo Keys", "Duo", "identity_provider", 0.8),
    (re.compile(r"(?:dwolla).{0,40}\b([a-zA-Z-0-9]{50})\b"), "Dwolla Keys", "Dwolla", "payment_system", 0.8),
    (re.compile(r"dt0[a-zA-Z]{1}[0-9]{2}\.[A-Z0-9]{24}\.[A-Z0-9]{64}"), "Dynatrace Token", "Dynatrace", "monitoring", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Easypost Api Key", "EasyPost", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:elastic.*?cloud.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Elastic Cloud Credentials", "Elastic", "data_storage", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Elastic Search Api Key", "Elastic", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:equinix.*?authentication.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Equinix Authentication Token", "Equinix", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:etsy.*?developer.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Etsy Developer Key", "Etsy", "e_commerce", 0.8),
    (re.compile(r"(?i)\b(\d{15,16}(\||%)[0-9a-z\-_]{27,40})(?:[\x60'\"\s;]|\\[nr]|$)"), "Facebook Access Token", "Meta", "social_network", 0.85),
    (re.compile(r"(?i)(?:facebook.*?app.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Facebook App Keys", "Meta", "social_network", 0.8),
    (re.compile(r"(?:fastly).{0,40}\b([A-Za-z0-9_-]{32})\b"), "Fastly Personal Token", "Fastly", "cdn", 0.8),
    (re.compile(r"(?:figma).{0,40}\b([0-9]{6}-[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})\b"), "Figma Personal Access Token", "Figma", "collaboration_tool", 0.85),
    (re.compile(r"(?i)(?:finicity.*?authentication.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Finicity Authentication Keys", "Finicity", "payment_system", 0.8),
    (re.compile(r"(?i)(?:firebase.*?id.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Firebase Id Token", "Google", "cloud_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Fish Audio Api Key", "Unknown", "unknown_or_deprecated", 0.8),
    (re.compile(r"\b(FLWSECK-[0-9a-z]{32}-X)\b"), "Flutterwave Api Key", "Flutterwave", "payment_system", 0.85),
    (re.compile(r"\b(fio-u-[0-9a-zA-Z_-]{64})\b"), "Frame Io Token", "Frame", "collaboration_tool", 0.85),
    (re.compile(r"(?i)(?:freshdesk.*?api.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Freshdesk Api Token", "Freshdesk", "crm", 0.8),
    (re.compile(r"(?i)(?:freshdesk.*?messaging.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Freshdesk Messaging Token", "Freshdesk", "crm", 0.8),
    (re.compile(r"(?i)(?:ftp.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Ftp Credentials", "Unknown", "data_storage", 0.85),
    (re.compile(r"(?i)(?:fullcontact.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Fullcontact Key", "FullContact", "crm", 0.8),
    (re.compile(r"(?:fullstory).{0,40}\b([a-zA-Z-0-9/+]{88})\b"), "Fullstory Api Key", "FullStory", "other", 0.8),
    (re.compile(r"(?i)(?:gemfury.*?deploy.*?or.*?push.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Gemfury Deploy Or Push Token", "Gemfury", "package_registry", 0.8),
    (re.compile(r"(?i)(?:gemfury.*?deploy.*?or.*?push.*?token.*?without.*?username)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Gemfury Deploy Or Push Token Without Username", "Gemfury", "package_registry", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Gemfury Full Access Token", "Gemfury", "package_registry", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Gemfury Full Access Token Without Username", "Gemfury", "package_registry", 0.8),
    (re.compile(r"(?i)(?:gitguardian.*?incident.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Gitguardian Incident Token", "GitGuardian", "monitoring", 0.85),
    (re.compile(r"(?i)(?:gitguardian.*?onboarding.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Gitguardian Onboarding Token", "GitGuardian", "monitoring", 0.85),
    (re.compile(r"(?i)(?:gitguardian.*?platform.*?magic.*?link)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Gitguardian Platform Magic Link", "GitGuardian", "internal", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Gitguardian Test Token Checked", "GitGuardian", "internal", 0.85),
    (re.compile(r"[gG][iI][tT][hH][uU][bB].*['|\"][0-9a-zA-Z]{35,40}['|\"]"), "Github App Keys", "GitHub", "version_control_platform", 0.85),
    (re.compile(r"(?:ghu|ghs)_[0-9a-zA-Z]{36}"), "Github App Token", "GitHub", "version_control_platform", 0.8),
    (re.compile(r"gho_[0-9a-zA-Z]{36}"), "Github Oauth App Keys", "GitHub", "version_control_platform", 0.8),
    (re.compile(r"(?:gitlab).{0,40}\b([a-zA-Z0-9\-=_]{20,22})\b"), "Gitlab Enterprise Token", "GitLab", "version_control_platform", 0.8),
    (re.compile(r"(?:gitlab).{0,40}\b([a-zA-Z0-9\-=_]{20,22})\b"), "Gitlab Feature Flags Client Token", "GitLab", "version_control_platform", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Gitlab Feature Flags Client Token With Project Id", "GitLab", "version_control_platform", 0.8),
    (re.compile(r"glimt-[0-9a-zA-Z_\-]{25}"), "Gitlab Incoming Mail Token", "GitLab", "version_control_platform", 0.85),
    (re.compile(r"(?:gitlab).{0,40}\b([a-zA-Z0-9\-=_]{20,22})\b"), "Gitlab Oauth Application Token", "GitLab", "version_control_platform", 0.85),
    (re.compile(r"(?:gitlab).{0,40}\b([a-zA-Z0-9\-=_]{20,22})\b"), "Gitlab Token", "GitLab", "version_control_platform", 0.8),
    (re.compile(r"(?:gitlab).{0,40}\b([a-zA-Z0-9\-=_]{20,22})\b"), "Gitlab Trigger Token", "GitLab", "version_control_platform", 0.8),
    (re.compile(r"\b(live_[0-9A-Za-z\_\-]{40}[ \"'\r\n]{1})"), "Gocardless Api Key", "GoCardless", "payment_system", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Google Cloud Express Api Key", "Google", "cloud_provider", 0.85),
    (re.compile(r"(ya29.[0-9A-Za-z-_]+)"), "Google Oauth2 Keys", "Google", "cloud_provider", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Grafana Cloud Api Key", "Grafana", "monitoring", 0.8),
    (re.compile(r"(?i)(?:grafana.*?personal.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Grafana Personal Token", "Unknown", "generic", 0.8),
    (re.compile(r"(?i)\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\x60'\"\s;]|\\[nr]|$)"), "Grafana Service Account Token", "Grafana", "monitoring", 0.8),
    (re.compile(r"(?i)\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\x60'\"\s;]|\\[nr]|$)"), "Grafana Service Account Token With Host", "Grafana", "monitoring", 0.8),
    (re.compile(r"(?:pat|sat)\.[a-zA-Z0-9_-]{22}\.[a-zA-Z0-9]{24}\.[a-zA-Z0-9]{20}"), "Harness Api Key", "Harness", "secret_management", 0.8),
    (re.compile(r"(?i)(?:hashicorp.*?consul.*?acl.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Hashicorp Consul Acl Token", "Unknown", "other", 0.8),
    (re.compile(r"(?i)(?:hashicorp.*?vault.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Hashicorp Vault Token", "HashiCorp", "secret_management", 0.8),
    (re.compile(r"(?i)(?:hashicorp.*?vault.*?unseal.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Hashicorp Vault Unseal Key", "HashiCorp", "secret_management", 0.8),
    (re.compile(r"(?:heroku).{0,40}\b([0-9Aa-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\b"), "Heroku Platform Key", "Heroku", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:huawei.*?open.*?platform.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Huawei Open Platform Keys", "Huawei", "other", 0.8),
    (re.compile(r"(?:hunter).{0,40}\b([a-z0-9_-]{40})\b"), "Hunter Api Key", "Hunter", "crm", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Ibm Api Connect Credentials", "IBM", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:ibm.*?cloud.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Ibm Cloud Key", "IBM", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:ibm.*?cos.*?hmac.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Ibm Cos Hmac Credentials", "IBM", "cloud_provider", 0.8),
    (re.compile(r"(?:host).{0,40}\b([a-z0-9]{14})\b"), "Influxdb Token With Host", "Influxdata", "data_storage", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Infracost Api Key", "Infracost", "other", 0.8),
    (re.compile(r"(?:tly).{0,40}\b([0-9A-Za-z]{60})\b"), "Instantly Api Key", "Instantly", "crm", 0.8),
    (re.compile(r"(?i)(?:ionic.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Ionic Token", "Ionic", "ci_cd", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Iyzico Api Keys", "Iyzico", "payment_system", 0.8),
    (re.compile(r"(?i)(?:jenkins.*?api.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Jenkins Api Token", "Jenkins", "ci_cd", 0.8),
    (re.compile(r"(?i)(?:jetbrains.*?teamcity.*?config.*?value)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Jetbrains Teamcity Config Value", "JetBrains", "ci_cd", 0.8),
    (re.compile(r"(?i)(?:jira.*?basic.*?auth)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Jira Basic Auth", "Atlassian", "collaboration_tool", 0.8),
    (re.compile(r"(?:jira).{0,40}\b([a-zA-Z-0-9]{24})\b"), "Jira Token", "Atlassian", "collaboration_tool", 0.8),
    (re.compile(r"(?i)(?:kairos.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Kairos Keys", "Kairos", "other", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Keycloak Access Token", "Keycloak", "identity_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Keycloak Api Keys", "Keycloak", "identity_provider", 0.8),
    (re.compile(r"refresh[_-]?token(=| =|:| :)"), "Keycloak Refresh Token", "Keycloak", "identity_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Kie Ai Api Key", "Kie", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Kimi Api Key", "Kimi", "ai", 0.8),
    (re.compile(r"(?i)(?:kinde.*?oauth.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Kinde Oauth Credentials", "Kinde", "identity_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Klaviyo Api Key", "Klaviyo", "messaging_system", 0.85),
    (re.compile(r"(?i)(?:kraken.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Kraken Keys", "Kraken", "cryptos", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Kubernetes Docker Secret", "Docker", "package_registry", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Lacework Api Keys", "Lacework", "monitoring", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Langfuse Credentials", "Langfuse", "other", 0.8),
    (re.compile(r"(?i)(?:ldap.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Ldap Credentials", "Unknown", "data_storage", 0.8),
    (re.compile(r"(?i)(?:linear.*?oauth2.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Linear Oauth2 Keys", "Linear", "collaboration_tool", 0.8),
    (re.compile(r"(?:linenotify).{0,40}\b([0-9A-Za-z]{43})\b"), "Line Notify Token", "Line", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:linkedin.*?oauth2.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Linkedin Oauth2 Keys", "Linkedin", "social_network", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Litellm Api Key", "LiteLLM", "ai", 0.8),
    (re.compile(r"(?:host).{0,40}\b([a-z0-9]{14})\b"), "Litellm Api Key Without Host", "LiteLLM", "ai", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Logflare Access Token", "Logflare", "unknown_or_deprecated", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Lovable Access Token", "Lovable", "ai", 0.8),
    (re.compile(r"git[_-]?token(=| =|:| :)"), "Lovable Git Token", "Lovable", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Mailersend Api Key", "MailerSend", "messaging_system", 0.85),
    (re.compile(r"(key-[0-9a-f]{32})"), "Mailgun Domain Sending Key", "Mailgun", "messaging_system", 0.8),
    (re.compile(r"(key-[0-9a-f]{32})"), "Mailgun Primary Key", "Mailgun", "messaging_system", 0.85),
    (re.compile(r"(?i)(?:mailjet.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mailjet Keys", "Mailjet", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:mapbox.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mapbox Token", "Mapbox", "other", 0.85),
    (re.compile(r"(?i)(?:mariadb.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mariadb Credentials", "Unknown", "data_storage", 0.8),
    (re.compile(r"(?:mattermost).{0,40}\b([A-Za-z0-9-_]{1,}.cloud.mattermost.com)\b"), "Mattermost Personal Token", "Mattermost", "messaging_system", 0.8),
    (re.compile(r"\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\x60'\"\s;]|\\[nr]|$)"), "Maxmind License Key", "MaxMind", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Mem0 Api Key", "Mem0", "ai", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Mercado Pago Access Token", "Mercado", "payment_system", 0.85),
    (re.compile(r"(?i)(?:mercado.*?pago.*?oauth)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mercado Pago Oauth", "Mercado", "payment_system", 0.8),
    (re.compile(r"(?:messagebird).{0,40}\b([A-Za-z0-9_-]{25})\b"), "Messagebird Key", "MessageBird", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:microsoft.*?azure.*?storage.*?account.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Microsoft Azure Storage Account Key", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Microsoft Azure Storage Connection String", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:microsoft.*?power.*?apps.*?webhook)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Microsoft Power Apps Webhook", "Microsoft", "cloud_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Modelscope Api Key", "Alibaba", "ai", 0.85),
    (re.compile(r"(?i)(?:momo.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Momo Credentials", "Momo", "payment_system", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Moneywave Api Key", "Flutterwave", "payment_system", 0.85),
    (re.compile(r"(?i)(?:mongodb.*?atlas.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mongodb Atlas Keys", "MongoDB", "data_storage", 0.8),
    (re.compile(r"(?i)(?:mssql.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mssql Credentials", "Microsoft", "data_storage", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Murf Api Key", "Murf", "ai", 0.85),
    (re.compile(r"(?i)(?:mysql.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Mysql Credentials", "Oracle", "data_storage", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "N8N Api Key", "n8n", "other", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Neoload Web Access Token", "NeoLoad", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Neon Api Key", "Neon", "data_storage", 0.85),
    (re.compile(r"(?i)(?:nessus.*?agent.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Nessus Agent Key", "Tenable", "monitoring", 0.8),
    (re.compile(r"(?:netlify).{0,40}\b([A-Za-z0-9_-]{43,45})\b"), "Netlify Token", "Netlify", "collaboration_tool", 0.8),
    (re.compile(r"(?:netlify).{0,40}\b([A-Za-z0-9_-]{43,45})\b"), "Netlify Token V2", "Netlify", "collaboration_tool", 0.8),
    (re.compile(r"\b(secret_[A-Za-z0-9]{43})\b"), "Notion Integration Token", "Notion", "collaboration_tool", 0.85),
    (re.compile(r"npm[_-]?token(=| =|:| :)"), "Npm Token", "npm", "package_registry", 0.8),
    (re.compile(r"(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\s\S-]{64,}?KEY(?: BLOCK)?-----"), "Nuclei Private Key", "Unknown", "private_key", 0.85),
    (re.compile(r"(?:nylas).{0,40}\b([0-9A-Za-z]{30})\b"), "Nylas Api Key", "Nylas", "messaging_system", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Obsidian Api Key", "Obsidian", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Odoo External Api Key", "Odoo", "crm", 0.8),
    (re.compile(r"(?i)(?:okta.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Okta Keys", "Okta", "identity_provider", 0.85),
    (re.compile(r"(?i)(?:okta.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Okta Token", "Okta", "identity_provider", 0.8),
    (re.compile(r"(?:host).{0,40}\b([a-z0-9]{14})\b"), "Okta Token With Host", "Okta", "identity_provider", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Openai Access Token", "OpenAI", "ai", 0.8),
    (re.compile(r"(?i)(?:openai.*?service.*?account)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Openai Service Account", "OpenAI", "ai", 0.85),
    (re.compile(r"auth[_-]?token(=| =|:| :)"), "Openclaw Auth Token", "OpenClaw", "ai", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Opencode Api Key", "OpenCode", "ai", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Oracle Credentials", "Oracle", "data_storage", 0.8),
    (re.compile(r"(https://outlook.office.com/webhook/[0-9a-f-]{36}@)"), "Outlook Team Webhook", "Microsoft", "messaging_system", 0.85),
    (re.compile(r"(?i)(?:ovh.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Ovh Keys", "OVH", "cloud_provider", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Packagecloud Token", "PackageCloud", "package_registry", 0.8),
    (re.compile(r"(?i)(?:pagerduty.*?authorization.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Pagerduty Authorization Token", "PagerDuty", "monitoring", 0.8),
    (re.compile(r"\b(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9\/\\_-]{17,}\.(?:[a-zA-Z0-9\/\\_-]{10,}={0,2})?)(?:[\x60'\"\s;]|\\[nr]|$)"), "Palantir Jwt", "Palantir", "other", 0.85),
    (re.compile(r"(?i)(?:payhere.*?app.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Payhere App Credentials", "Payhere", "payment_system", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Payhere Merchant Secret", "Payhere", "payment_system", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Paymob Api Key", "Paymob", "payment_system", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Paymob Hmac Secret", "Paymob", "payment_system", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Paymob Secret Key", "Paymob", "payment_system", 0.8),
    (re.compile(r"(?i)(?:paypal.*?braintree.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Paypal Braintree Keys", "PayPal", "payment_system", 0.8),
    (re.compile(r"\b([A-Za-z0-9_\.]{69}-[A-Za-z0-9_\.]{10})\b"), "Paypal Oauth2 Keys", "PayPal", "payment_system", 0.8),
    (re.compile(r"\b(sk\_[a-z]{1,}\_[A-Za-z0-9]{40})\b"), "Paystack Key", "Paystack", "payment_system", 0.85),
    (re.compile(r"(?:pepipost|netcore).{0,40}\b([a-zA-Z-0-9]{32})\b"), "Pepipost Key", "Pepipost", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:pingdom.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Pingdom Token", "Pingdom", "monitoring", 0.8),
    (re.compile(r"(?i)(?:pingidentity.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Pingidentity Keys", "PingIdentity", "identity_provider", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Plaid Access Token", "Plaid", "payment_system", 0.8),
    (re.compile(r"(?i)(?:plaid.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Plaid Keys", "Plaid", "payment_system", 0.8),
    (re.compile(r"\b(pscale_oauth_[\w=\.-]{32,64})(?:[\x60'\"\s;]|\\[nr]|$)"), "Planetscale Oauth Token", "PlanetScale", "data_storage", 0.85),
    (re.compile(r"auth[_-]?token(=| =|:| :)"), "Plivo Auth Tokens", "Plivo", "messaging_system", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Polyapi Api Key", "PolyAPI", "other", 0.8),
    (re.compile(r"(?i)(?:postgresql.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Postgresql Credentials", "Unknown", "data_storage", 0.8),
    (re.compile(r"\b(phc_[a-zA-Z0-9_]{43})\b"), "Posthog Personal Api Key", "PostHog", "other", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Posthog Project Api Key", "Unknown", "other", 0.8),
    (re.compile(r"\b(PMAK-[a-zA-Z-0-9]{59})\b"), "Postman Api Key", "Postman", "messaging_system", 0.85),
    (re.compile(r"(?:postmark).{0,40}\b([0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})\b"), "Postmark Token", "Postmark", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:proxmox.*?api.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Proxmox Api Token", "Proxmox", "other", 0.8),
    (re.compile(r"(?i)(?:pubnub.*?subscription.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Pubnub Subscription Key", "PubNub", "messaging_system", 0.85),
    (re.compile(r"(?:pushbullet).{0,40}\b([A-Za-z0-9_\.]{34})\b"), "Pushbullet Api Key", "Pushbullet", "other", 0.8),
    (re.compile(r"(?i)(?:pusher.*?channels.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Pusher Channels Keys", "Pusher", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:python.*?package.*?index.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Python Package Index Key", "Python", "package_registry", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Qq Robot Api Keys", "QQ", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:rails.*?master.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Rails Master Key", "Unknown", "private_key", 0.8),
    (re.compile(r"(?:rapidapi).{0,40}\b([A-Za-z0-9_-]{50})\b"), "Rapidapi Key", "RapidAPI", "other", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Recaptcha Key", "Google", "other", 0.8),
    (re.compile(r"(?i)(?:redis.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Redis Credentials", "Redis", "data_storage", 0.8),
    (re.compile(r"(?i)(?:redis.*?server.*?password)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Redis Server Password", "Redis", "data_storage", 0.8),
    (re.compile(r"(?i)(?:redshift.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Redshift Credentials", "Amazon", "data_storage", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Retell Api Key", "Retell", "ai", 0.85),
    (re.compile(r"(?i)(?:salesforce.*?oauth2.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Salesforce Oauth2 Keys", "Salesforce", "crm", 0.85),
    (re.compile(r"refresh[_-]?token(=| =|:| :)"), "Salesforce Refresh Tokens", "Salesforce", "crm", 0.85),
    (re.compile(r"(?i)(?:sanity.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sanity Token", "Sanity", "other", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Sap Ai Core Credentials", "SAP", "ai", 0.8),
    (re.compile(r"(?i)(?:sap.*?oauth.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sap Oauth Credentials", "SAP", "other", 0.8),
    (re.compile(r"(?i)(?:scaleway.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Scaleway Token", "Scaleway", "cloud_provider", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Scalr Api Access Token", "Scalr", "other", 0.8),
    (re.compile(r"(?:scraperapi).{0,40}\b([a-z0-9]{32})\b"), "Scraper Api Key", "Scraper", "other", 0.8),
    (re.compile(r"(?i)(?:segment.*?workspace.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Segment Workspace Key", "Segment", "crm", 0.8),
    (re.compile(r"(SG\.[\w\-_]{20,24}\.[\w\-_]{39,50})\b"), "Sendgrid Key", "SendGrid", "messaging_system", 0.85),
    (re.compile(r"(?i)(?:sendinblue.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sendinblue Key", "Sendinblue", "crm", 0.85),
    (re.compile(r"auth[_-]?token(=| =|:| :)"), "Sentry Org Auth Token", "Sentry", "monitoring", 0.8),
    (re.compile(r"(?i)(?:serpapi.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Serpapi Token", "SerpApi", "other", 0.8),
    (re.compile(r"\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\x60'\"\s;]|\\[nr]|$)"), "Shippo Api Token", "Shippo", "e_commerce", 0.85),
    (re.compile(r"(?:shodan).{0,40}\b([a-zA-Z0-9]{32})\b"), "Shodan Key", "Shodan", "other", 0.8),
    (re.compile(r"app[_-]?token(=| =|:| :)"), "Shopify Generic App Token", "Shopify", "e_commerce", 0.85),
    (re.compile(r"(?i)(?:shopify.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Shopify Keys", "Shopify", "e_commerce", 0.8),
    (re.compile(r"app[_-]?token(=| =|:| :)"), "Shopify Private App Token", "Shopify", "e_commerce", 0.85),
    (re.compile(r"xox[baprs]-[0-9a-zA-Z-]{10,72}"), "Slack Configuration Refresh Token", "Slack", "messaging_system", 0.85),
    (re.compile(r"xox[baprs]-[0-9a-zA-Z-]{10,72}"), "Slack Configuration Token", "Slack", "messaging_system", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Slack Signing Secret", "Slack", "messaging_system", 0.8),
    (re.compile(r"xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}"), "Slack User Token", "Slack", "messaging_system", 0.85),
    (re.compile(r"(?i)(?:smb.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Smb Credentials", "Unknown", "data_storage", 0.85),
    (re.compile(r"(?i)(?:smtp.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Smtp Credentials", "Unknown", "messaging_system", 0.8),
    (re.compile(r"(?:snyk).{0,40}\b([0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})\b"), "Snyk Key", "Snyk", "code_analysis", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Socket Dev Api Key", "Socket", "code_analysis", 0.8),
    (re.compile(r"(?i)(?:solr.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Solr Credentials", "Unknown", "data_storage", 0.85),
    (re.compile(r"sonar.{0,50}(?:\"|'|`)?[0-9a-f]{40}(?:\"|'|`)?"), "Sonarqube Token", "SonarQube", "code_analysis", 0.8),
    (re.compile(r"(?:host).{0,40}\b([a-z0-9]{14})\b"), "Sonarqube Token With Host", "SonarQube", "code_analysis", 0.8),
    (re.compile(r"(?i)(?:sourcegraph.*?enterprise.*?subscription.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sourcegraph Enterprise Subscription Token", "Sourcegraph", "code_analysis", 0.85),
    (re.compile(r"(?i)(?:sourcegraph.*?license.*?key.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sourcegraph License Key Token", "Sourcegraph", "code_analysis", 0.85),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Sourcegraph User Gateway Access Token", "Sourcegraph", "code_analysis", 0.85),
    (re.compile(r"(?i)(?:sparkpost.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sparkpost Key", "SparkPost", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:splunk.*?authentication.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Splunk Authentication Token", "Splunk", "monitoring", 0.8),
    (re.compile(r"(?i)(?:splunk.*?user.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Splunk User Credentials", "Splunk", "monitoring", 0.8),
    (re.compile(r"(?i)(?:spotify.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Spotify Keys", "Spotify", "other", 0.8),
    (re.compile(r"(?i)(?:sqreen.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Sqreen Token", "Sqreen", "code_analysis", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Square Credentials", "Square", "payment_system", 0.85),
    (re.compile(r"(?:square).{0,40}(EAAA[a-zA-Z0-9\-\+\=]{60})"), "Square Token", "Square", "payment_system", 0.85),
    (re.compile(r"-----BEGIN OPENSSH PRIVATE KEY-----"), "Ssh Credentials", "Unknown", "remote_access", 0.8),
    (re.compile(r"(?:sslmate).{0,40}\b([a-zA-Z0-9]{36})\b"), "Sslmate Api Key", "SSLMate", "identity_provider", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Stackhawk Api Key", "StackHawk", "code_analysis", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Stitch Api Key", "Google", "ai", 0.85),
    (re.compile(r"(?i)(?:stream.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Stream Keys", "Stream", "messaging_system", 0.8),
    (re.compile(r"[rs]k_live_[a-zA-Z0-9]{20,30}"), "Stripe Keys", "Stripe", "payment_system", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Supabase Api Key", "Supabase", "data_storage", 0.8),
    (re.compile(r"\b(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9\/\\_-]{17,}\.(?:[a-zA-Z0-9\/\\_-]{10,}={0,2})?)(?:[\x60'\"\s;]|\\[nr]|$)"), "Supabase Jwt Secret", "Supabase", "data_storage", 0.8),
    (re.compile(r"surge[_-]?token(=| =|:| :)"), "Surge Token", "Surge", "payment_system", 0.8),
    (re.compile(r"\b(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9\/\\_-]{17,}\.(?:[a-zA-Z0-9\/\\_-]{10,}={0,2})?)(?:[\x60'\"\s;]|\\[nr]|$)"), "Surrealdb Cloud Jwt Token", "SurrealDB", "data_storage", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Tailscale Api Key", "Tailscale", "remote_access", 0.85),
    (re.compile(r"(?i)(?:tailscale.*?oauth.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Tailscale Oauth Key", "Tailscale", "remote_access", 0.85),
    (re.compile(r"(?i)(?:tailscale.*?pre.*?auth.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Tailscale Pre Auth Key", "Tailscale", "remote_access", 0.85),
    (re.compile(r"(?i)(?:tailscale.*?scim.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Tailscale Scim Key", "Tailscale", "remote_access", 0.85),
    (re.compile(r"(?i)(?:tailscale.*?webhook.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Tailscale Webhook Key", "Tailscale", "remote_access", 0.85),
    (re.compile(r"(?i)(?:tencent.*?cloud.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Tencent Cloud Keys", "Tencent", "cloud_provider", 0.8),
    (re.compile(r"(?:tomtom).{0,40}\b([0-9Aa-zA-Z]{32})\b"), "Tomtom Api Key", "TomTom", "other", 0.8),
    (re.compile(r"(?i)(?:travis.*?personal.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Travis Personal Token", "Travis", "ci_cd", 0.8),
    (re.compile(r"(?i)(?:trello.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Trello Keys", "Trello", "collaboration_tool", 0.8),
    (re.compile(r"(?i)(?:twilio.*?master.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Twilio Master Credentials", "Twilio", "messaging_system", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Twitch Api Keys", "Twitch", "other", 0.8),
    (re.compile(r"(?i)(?:twitter.*?access.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Twitter Access Keys", "Twitter", "social_network", 0.8),
    (re.compile(r"(?i)[\w.-]{0,50}?(?:typeform)(?:[ \t\w.-]{0,20})[\s'\"]{0,3}(?:=|>|:{1,3}=|\|\||:|=>|\?=|,)[\x60'\"\s=]{0,5}(tfp_[a-z0-9\-_\.=]{59})(?:[\x60'\"\s;]|\\[nr]|$)"), "Typeform Api Token", "Typeform", "crm", 0.8),
    (re.compile(r"(?i)(?:uber.*?server.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Uber Server Token", "Uber", "other", 0.8),
    (re.compile(r"\b(BBFF-[0-9a-zA-Z]{30})\b"), "Ubidots Token", "Ubidots", "other", 0.85),
    (re.compile(r"(?i)(?:upstash.*?redis.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Upstash Redis Credentials", "Unknown", "data_storage", 0.8),
    (re.compile(r"(?i)(?:vapid.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Vapid Key", "Unknown", "messaging_system", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Vapi Api Key", "Vapi", "ai", 0.8),
    (re.compile(r"(?:vercel).{0,40}\b([a-zA-Z0-9]{24})\b"), "Vercel Api Access Token", "Vercel", "collaboration_tool", 0.8),
    (re.compile(r"(?:vercel).{0,40}\b([a-zA-Z0-9]{24})\b"), "Vercel Blob Token", "Vercel", "data_storage", 0.85),
    (re.compile(r"(?:vercel).{0,40}\b([a-zA-Z0-9]{24})\b"), "Vercel Oidc Token", "Vercel", "collaboration_tool", 0.8),
    (re.compile(r"(?:virustotal).{0,40}\b([a-f0-9]{64})\b"), "Virustotal Api Key", "VirusTotal", "other", 0.8),
    (re.compile(r"(?i)(?:visa.*?basic.*?auth)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Visa Basic Auth", "Visa", "payment_system", 0.8),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Vkontakte Access Token", "VKontakte", "social_network", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Volcengine Api Key", "Volcengine", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:vonage.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Vonage Keys", "Vonage", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:vultr.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Vultr Key", "Vultr", "cloud_provider", 0.8),
    (re.compile(r"(?i)(?:webex.*?app.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Webex App Keys", "Webex", "messaging_system", 0.8),
    (re.compile(r"(?:webflow).{0,40}\b([a-zA0-9]{64})\b"), "Webflow Api Token", "Webflow", "e_commerce", 0.8),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Wechat App Keys", "Tencent", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:wepay.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Wepay Token", "WePay", "payment_system", 0.85),
    (re.compile(r"(?i)(?:wireguard.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Wireguard Credentials", "WireGuard", "payment_system", 0.8),
    (re.compile(r"(?i)(?:wiz.*?oauth.*?credentials)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Wiz Oauth Credentials", "Wiz", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Workato Api Key", "Workato", "other", 0.85),
    (re.compile(r"access[_-]?token(=| =|:| :)"), "Xray Access Token", "JFrog", "package_registry", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "X Ai Api Key", "X", "ai", 0.8),
    (re.compile(r"(?i)(?:yahoo.*?oauth2.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Yahoo Oauth2 Keys", "Yahoo", "other", 0.85),
    (re.compile(r"(?:yandex).{0,40}\b([a-z0-9A-Z.]{83})\b"), "Yandex Predictor Api Key", "Yandex", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Yelp Api Key", "Yelp", "other", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Yookassa Api Key", "YooMoney", "payment_system", 0.85),
    (re.compile(r"(?:yousign).{0,40}\b([0-9a-z]{32})\b"), "Yousign Api Key", "Yousign", "other", 0.8),
    (re.compile(r"https://(?:www.)?hooks\.zapier\.com/hooks/catch/[A-Za-z0-9]+/[A-Za-z0-9]+/"), "Zapier Webhook Url", "Zapier", "other", 0.85),
    (re.compile(r"-----BEGIN EC PRIVATE KEY-----"), "Zegocloud Secret", "ZEGOCLOUD", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:zendesk.*?token)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Zendesk Token", "Zendesk", "crm", 0.8),
    (re.compile(r"(?i)(?:zillow.*?key)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Zillow Key", "Zillow", "other", 0.85),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Zoho Api Key", "Zoho", "crm", 0.85),
    (re.compile(r"(?i)(?:zoho.*?oauth2.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Zoho Oauth2 Keys", "Zoho", "collaboration_tool", 0.85),
    (re.compile(r"\b(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9\/\\_-]{17,}\.(?:[a-zA-Z0-9\/\\_-]{10,}={0,2})?)(?:[\x60'\"\s;]|\\[nr]|$)"), "Zoom Api Jwt", "Zoom", "messaging_system", 0.8),
    (re.compile(r"\b(ey[a-zA-Z0-9]{17,}\.ey[a-zA-Z0-9\/\\_-]{17,}\.(?:[a-zA-Z0-9\/\\_-]{10,}={0,2})?)(?:[\x60'\"\s;]|\\[nr]|$)"), "Zoom Api Jwt Keys", "Zoom", "messaging_system", 0.8),
    (re.compile(r"api[_-]?key(=| =|:| :)"), "Zoom Api Keys", "Zoom", "messaging_system", 0.8),
    (re.compile(r"(?i)(?:zoom.*?sdk.*?keys)[\s=:]+([a-zA-Z0-9_\-]{16,})"), "Zoom Sdk Keys", "Zoom", "messaging_system", 0.8),
]
